// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function CountrySuggestion(Props) {
  var results = Props.results;
  var clickedValue = Props.clickedValue;
  var options = Belt_Array.map(results, (function (country) {
          return React.createElement("div", {
                      key: "country-" + country.id,
                      className: "flag-option",
                      onClick: (function (param) {
                          var value = country.value;
                          var label = country.label;
                          Curry._2(clickedValue, value, label);
                          console.log(value);
                          
                        })
                    }, React.createElement("img", {
                          className: "flag-icon",
                          alt: "United States",
                          src: "http://purecatamphetamine.github.io/country-flag-icons/3x2/US.svg"
                        }), React.createElement("span", {
                          className: "option-field"
                        }, country.label), React.createElement("input", {
                          key: "country-input-" + country.id,
                          type: "hidden",
                          value: country.value
                        }));
        }));
  return React.createElement("div", {
              className: "row autocomplete-items",
              id: "autocomplete-list"
            }, options);
}

var make = CountrySuggestion;

exports.make = make;
/* react Not a pure module */
