// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function CountrySuggestion(Props) {
  var results = Props.results;
  var options = Belt_Array.map(results, (function (country) {
          return React.createElement("li", {
                      key: country.value
                    }, country.label);
        }));
  return React.createElement("div", {
              className: "container"
            }, React.createElement("ul", undefined, options));
}

var make = CountrySuggestion;

exports.make = make;
/* react Not a pure module */
