// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var FormControl = require("react-bootstrap/FormControl").default;

var FormControl$1 = {};

function CountrySelect(Props) {
  return React.createElement("div", undefined, React.createElement(FormControl, {
                  placeholder: "Search..."
                }));
}

var make = CountrySelect;

exports.FormControl = FormControl$1;
exports.make = make;
/* react Not a pure module */
